# vim: set expandtab tabstop=2 shiftwidth=2 softtabstop=2:
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 25
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Halifax

# {{{ customizations

  customize:
    group.all_devices:
      hidden: false
    group.all_scripts:
      hidden: false
    group.all_automations:
      hidden: false
    group.all_booleans:
      hidden: false
    group.all_lights:
      hidden: false
    group.all_switches:
      hidden: false

# }}}
# {{{ misc

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Wemo switches are not always being discovered automatically.
wemo:
  static:
    - 192.168.2.80
    - 192.168.2.81

# Hue lights are not being discovered automaically.
light:
  platform: hue
  host: 192.168.2.120
  allow_unreachable:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

ifttt:
  key: !secret ifttt_key

ffmpeg:
  run_test: False

# Enable text-to-speech
tts:
  - platform: google

# }}}
# {{{ zones

zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 50
  icon: mdi:home

zone silverorange:
  name: silverorange
  latitude: !secret silverorange_latitude
  longitude: !secret silverorange_longitude
  radius: 50
  icon: mdi:domain

zone upstreet:
  name: Upstreet
  latitude: !secret upstreet_latitude
  longitude: !secret upstreet_longitude
  radius: 50
  icon: mdi:beer

zone innovatia:
  name: Innovatia
  latitude: !secret innovatia_latitude
  longitude: !secret innovatia_longitude
  radius: 100
  icon: mdi:domain

zone walmart:
  name: "Walmart"
  latitude: !secret walmart_latitude
  longitude: !secret walmart_longitude
  radius: 100
  icon: mdi:shopping

zone churchill_arms:
  name: "Churchill Arms"
  latitude: !secret churchill_arms_latitude
  longitude: !secret churchill_arms_longitude
  radius: 50
  icon: mdi:beer

zone yyc:
  name: "Calgary Airport"
  latitude: 51.125061
  longitude: -114.016889
  radius: 100
  icon: mdi:airplane

zone yyg:
  name: "Charlottetown Airport"
  latitude: 46.285705
  longitude: -63.129078
  radius: 100
  icon: mdi:airplane

zone yeg:
  name: "Edmonton Airport"
  latitude: 53.327848
  longitude: -113.566524
  radius: 100
  icon: mdi:airplane

zone yhz:
  name: "Halifax Airport"
  latitude: 44.887088
  longitude: -63.515278
  radius: 400
  icon: mdi:airplane

zone yul:
  name: "Montreal Airport"
  latitude: 45.469738
  longitude: -73.744919
  radius: 400
  icon: mdi:airplane

zone yyz:
  name: "Pearson Airport"
  latitude: 43.679232
  longitude: -79.620109
  radius: 1000
  icon: mdi:airplane

zone ytz:
  name: "Toronto City Central Airport"
  latitude: 43.628482
  longitude: -79.395958
  radius: 400
  icon: mdi:airplane

zone yjz:
  name: "Saint John Airport"
  latitude: 45.326501
  longitude: -65.888867
  radius: 400
  icon: mdi:airplane

zone yyt:
  name: "St. John's Airport"
  latitude: 47.621210
  longitude: -52.742443
  radius: 400
  icon: mdi:airplane

# }}}
# {{{ frontend

# Enables the frontend
frontend:

http:
  base_url: ha.demontbrun.com
  api_password: !secret http_api_password
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  use_x_forwarded_for: True
  trusted_networks:
    - 192.168.2.0/24
    - 127.0.0.1

# }}}
# {{{ Sensors

sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol

  - platform: wunderground
    api_key: !secret wunderground_api_key
    monitored_conditions:
      - alerts
      - feelslike_c
      - heat_index_c
      - pressure_trend
      - relative_humidity
      - solarradiation
      - temp_c
      - UV
      - visibility_km
      - weather
      - wind_degrees
      - wind_gust_kph
      - wind_kph

  - platform: yweather
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature

binary_sensor:
  - platform: ffmpeg
    name: Front Door
    tool: motion
    input: http://192.168.2.92:8080/video

# }}}
# {{{ Presence Trackers

device_tracker:
  - platform: asuswrt
    host: 192.168.2.249
    username: admin
    mode: ap
    protocol: ssh
    ssh_key: /Users/gervais/.ssh/id_rsa

  - platform: nmap_tracker
    hosts: 192.168.2.1-25

  - platform: nmap_tracker
    hosts: 192.168.2.26-50

  - platform: nmap_tracker
    hosts: 192.168.2.51-75

  - platform: nmap_tracker
    hosts: 192.168.2.76-100

  - platform: nmap_tracker
    hosts: 192.168.2.101-125

  - platform: nmap_tracker
    hosts: 192.168.2.126-150

  - platform: nmap_tracker
    hosts: 192.168.2.151-175

  - platform: nmap_tracker
    hosts: 192.168.2.176-200

  - platform: nmap_tracker
    hosts: 192.168.2.201-225

  - platform: nmap_tracker
    hosts: 192.168.2.226-254

  - platform: icloud
    username: !secret icloud_username
    password: !secret icloud_password
    account_name: !secret icloud_account_name

  - platform: ping
    hosts:
      Jennifer: jen-phone
      Cameron: cam-phone

# }}}
# {{{ Toggles

input_boolean:
  loop_livingcolours:
    name: Loop Livingroom Colours
    initial: off
    icon: mdi:spotlight

input_slider:
  livingroom_brightness:
    name: Livingroom Brightness
    initial: 255
    min: 0
    max: 255
    step: 1

# }}}
# {{{ Security Cams

camera:
  - name: 'Front Door'
    platform: mjpeg
    mjpeg_url: http://192.168.2.92:8080/video

# }}}

group: !include groups.yml
scene: !include scenes.yml
automation: !include automations.yml
