# vim: set expandtab tabstop=2 shiftwidth=2 softtabstop=2:

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 7
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Halifax
  # Allow homeassistant to write to snapshots dir
  allowlist_external_dirs:
    - /var/www/html/snapshots
    - /etc/homeassistant/file_restore
  customize: !include customize.yaml

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.2.0/24
        - 127.0.0.1

default_config:

# {{{ Asus

asuswrt:
  host: 192.168.2.1
  username: !secret router_username
  ssh_key: /home/homeassistant/.ssh/id_rsa

# }}}
# {{{ Alexa

alexa:
  smart_home:
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: !secret alexa_client_id
    client_secret: !secret alexa_client_secret
    filter:
      include_domains:
        - light
        - scene
      include_entities:
        - media_player.roku_3
        - media_player.roku_sunroom
        - media_player.sonos
        - switch.switch4

# }}}
# {{{ Circadian Lighting & mqtt switch

circadian_lighting:
switch:
  - platform: circadian_lighting
    name: Bedroom Circadian
    lights_xy:
      - light.bedroom0
      - light.bedroom1
      - light.bedroom2
      - light.bedroom3
      - light.bedroom4

  - platform: circadian_lighting
    name: Office Circadian
    disable_brightness_adjust: true
    lights_xy:
      - light.office0
      - light.office1
      - light.office2

  - platform: mqtt
    name: "Zigbee2mqtt Main join"
    state_topic: "zigbee2mqtt/bridge/config/permit_join"
    command_topic: "zigbee2mqtt/bridge/config/permit_join"
    payload_on: "true"
    payload_off: "false"

# }}}
# {{{ frontend

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

http:
  #ssl_certificate: !secret http_ssl_certificate
  #ssl_key: !secret http_ssl_key
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

# }}}
# {{{ Lights

light:
  # Make basement switch act like a light
  - platform: switch
    name: Basement Light
    entity_id: switch.basement_light

  # Make Bathroom switches act like lights
  - platform: switch
    name: Bathroom0
    entity_id: switch.bathroom0
  - platform: switch
    name: Bathroom1
    entity_id: switch.bathroom1
  - platform: switch
    name: Bathroom2
    entity_id: switch.bathroom2

  # Make Livingroom switch act like a light
  - platform: switch
    name: Livingroom Shelves
    entity_id: switch.switch2

  # Make Office Table switch act like a light
  - platform: switch
    name: Office Table
    entity_id: switch.switch0

  # Make Outdoor switches act like lights
  - platform: switch
    name: Backdoor
    entity_id: switch.outdoor_backdoor
  - platform: switch
    name: Deck lights
    entity_id: switch.outdoor_deck_lights

  # Make Sunroom switch act like light
  - platform: switch
    name: Saltlick
    entity_id: switch.switch5

  - platform: group
    name: Bathroom lights
    entities:
      - light.bathroom0
      - light.bathroom1
      - light.bathroom2

  - platform: group
    name: Bedroom lights
    entities:
      - light.bedroom0
      - light.bedroom1
      - light.bedroom2
      - light.bedroom3
      - light.bedroom4

  - platform: group
    name: Dining room lights
    entities:
      - light.diningroom0
      - light.diningroom1
      - light.diningroom2
      - light.diningroom3
      - light.diningroom4
      - light.diningroom5
      - light.diningroom6

  - platform: group
    name: Dressing room lights
    entities:
      - light.dressing_room0
      - light.dressing_room1
      - light.dressing_room2
      - light.dressing_room3

  - platform: group
    name: Hallway lights
    entities:
      - light.stairs_back
      - light.cherub
      - light.foyer
      - light.hallway_back
      - light.hallway_table
      - light.hallway_wall
      - light.hallway_upstairs

  - platform: group
    name: Kitchen lights
    entities:
      - light.kitchen_island
      - light.kitchen_pots
      - light.kitchen_swirly0
      - light.kitchen_swirly1

  - platform: group
    name: Livingroom lamps
    entities:
      - light.lamp0
      - light.lamp1
      - light.lamp2

  - platform: group
    name: Livingroom lights
    entities:
      - light.livingroom_lamps
      - light.livingroom_chandeliers
      - light.livingroom_shelves

  - platform: group
    name: Livingroom Chandeliers
    entities:
      - light.living_room_pendants0
      - light.living_room_pendants1

  - platform: group
    name: Main floor lights
    entities:
      - light.dining_room_lights
      - light.hallway_lights
      - light.kitchen_lights
      - light.livingroom_lights
      - light.office_lights
      - light.main_floor_bathroom_light

  - platform: group
    name: Office lights
    entities:
      - light.office_lamp
      - light.office_main_light
      - light.office_wall
      - light.office_table

  - platform: group
    name: Outdoor lights
    entities:
      - light.front_door
      - light.backdoor
      - light.deck_lights

  - platform: group
    name: Second floor lights
    entities:
      - light.bedroom_lights
      - light.dressing_room_lights
      - light.hallway_back
      - light.hallway_upstairs
      - light.spare_room_lights
      - light.sunroom_lights
      - light.upstairsbathroom
      - light.stairs_back

  - platform: group
    name: Spare room lights
    entities:
      - light.spare0
      - light.spare1

  - platform: group
    name: Sunroom lights
    entities:
      - light.saltlick
      - light.sunroom0
      - light.sunroom1
      - light.sunroom2
      - light.sunroom3
      - light.sunroom4

  - platform: group
    name: Washroom lights
    entities:
      - light.main_floor_bathroom_light
      - light.upstairsbathroom

#  }}}
# {{{ Media Players

media_player:

# }}}
# {{{ Misc

# Enable frontend configuration
config:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Set logging level
logger:
  default: error
  logs:
    homeassistant.components.camera: fatal
    homeassistant.components.media_player.roku: fatal
    homeassistant.components.http.ban: warning

# Homekit
homekit:
  auto_start: false
  filter:
    include_domains:
      - light
      - media_player
      - switch

# Lutron Caseta
lutron_caseta:
  host: 192.168.2.121
  keyfile:  '/etc/homeassistant/lutron/caseta.key'
  certfile: '/etc/homeassistant/lutron/caseta.crt'
  ca_certs: '/etc/homeassistant/lutron/caseta-bridge.crt'

# Enables support for tracking state changes over time.
history:
  include:
    entities:
      - person.gail
      - person.gervais
      - person.jennifer

# Setup recorder and logbook
recorder:
logbook:
  exclude:
    domains:
      - device_tracker
      - sun

image:

# Track the sun
sun:

ifttt:
  key: !secret ifttt_key

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# Enable Mobile App component
mobile_app:

downloader:
  download_dir: /var/www/html/snapshots

system_health:

# }}}
# {{{ mqtt

mqtt:
  discovery: true
  broker: 127.0.0.1
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120

# Input select for Zigbee2mqtt debug level
input_select:
  zigbee2mqtt_log_level:
    name: Zigbee2mqtt Log Level
    options:
      - debug
      - info
      - warn
      - error
    initial: info
    icon: mdi:format-list-bulleted

# Input text to input Zigbee2mqtt friendly_name for scripts
input_text:
  zigbee2mqtt_old_name:
    name: Zigbee2mqtt Old Name
  zigbee2mqtt_new_name:
    name: Zigbee2mqtt New Name
  zigbee2mqtt_remove:
    name: Zigbee2mqtt Remove

# }}}
# {{{ Notify

notify:
  - name: zulip
    platform: rest
    resource: !secret zulip_notify_resource
    method: POST_JSON
    title_param_name: topic

  - name: ecobee
    platform: ecobee

# }}}
# {{{ Persons

person:
  - name: Gail
    id: gail1968
    user_id: 09f60884ba844227a9b3c2d54fb341e2
    device_trackers:
      - device_tracker.gail_iphone
      - device_tracker.gail3
  - name: Cameron
    id: cam1995
    device_trackers:
      - device_tracker.camphone
      - device_tracker.cam_fing
  - name: Grant
    id: grant1994
    device_trackers:
      - device_tracker.grantphone
      - device_tracker.grant_fing
  - name: Jennifer
    id: jen2000
    device_trackers:
      - device_tracker.jen_phone
      - device_tracker.jen_fing

# }}}
# {{{ Presence Trackers

owntracks:

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.2.10-15
    home_interval: 5
    interval_seconds: 120
    new_device_defaults:
      track_new_devices: true

  - platform: nmap_tracker
    hosts: 192.168.2.250-254
    home_interval: 5
    interval_seconds: 120
    new_device_defaults:
      track_new_devices: true

  - platform: ping
    count: 3
    hosts:
      bell_internet: 1.1.1.1

  - platform: huesensor

# }}}
# {{{ Programmable thermostat

# Commenting this out. It's messing with my window fan
climate:
  - platform: programmable_thermostat
    name: Bedroom Heater
    heater:
      - switch.switch4
    actual_temp_sensor: sensor.master_bedroom_temperature
    min_temp: 14
    max_temp: 20
    target_temp_sensor: sensor.thermostat_program
    tolerance: 0.3
    hvac_options: 7
    auto_mode: all

  - platform: programmable_thermostat
    name: Jenroom Heater
    heater:
      - switch.switch6
    actual_temp_sensor: sensor.jennifer_room_temperature
    min_temp: 14
    max_temp: 20
    target_temp_sensor: sensor.thermostat_jen_program
    tolerance: 0.3
    hvac_options: 7
    auto_mode: all

# }}}
## {{{ Rest Commands

rest_command:
  sabnzb_api:
    url: !secret sabnzbd_rest_url

  take_a_picture:
    url: http://192.168.2.92:8080/photo_save_only.jpg

## }}}
# {{{ Ring

ring:
  username: !secret ring_username
  password: !secret ring_password

# }}}
# {{{ Security Cams

camera:
  - platform: ring
  - platform: environment_canada

# }}}
# {{{ Sensors

sensor:
  - platform: whois
    domain: demontbrun.com
    name: deMontbrun DNS Expiry

  - platform: season

  - platform: cert_expiry
    host: !secret http_base_url

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use_percent
        arg: /boot
      - type: disk_use_percent
        arg: /media/wine
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: swap_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use
      - type: last_boot

  - platform: command_line
    name: 'Grater uptime'
    command: cat /proc/uptime | awk '{ print $1 }'
    scan_interval: 60
    unit_of_measurement: minutes
    value_template: >-
      {% set uptime = value | int %}
      {% set minutes = (uptime / 60 ) | int %}
      {{ minutes }}

  - platform: uptime
    name: 'HASS uptime'
    unit_of_measurement: hours

  - platform: moon

  - platform: command_line
    name: 'filesize_db'
    command: 'stat -c %s "/etc/homeassistant/home-assistant_v2.db"'
    unit_of_measurement: 'MB'
    value_template: '{{ (value|int / 1024 / 1024)|round(1) }}'
    scan_interval: 900

  # Data for programmable thermostats
  - platform: file_restore
    unit_of_measurement: '°C'
    file_path: '/etc/homeassistant/file_restore/thermostat_program.csv'
    name: Thermostat Program
    length: day
    detail: hour

  - platform: file_restore
    unit_of_measurement: '°C'
    file_path: '/etc/homeassistant/file_restore/thermostat_jen_program.csv'
    name: Thermostat Jen Program
    length: day
    detail: hour

  - platform: template
    sensors:
      kitchen_battery_level:
        friendly_name: 'Kitchen Battery Level'
        value_template: '{{ states.binary_sensor.kitchen_motion_sensor.attributes.battery }}'
        unit_of_measurement: '%'
        device_class: battery
      kitchen_lumens:
        friendly_name: 'Kitchen Lumens'
        value_template: '{{ states.binary_sensor.kitchen_motion_sensor.attributes.light_level }}'
        unit_of_measurement: Lumens
        device_class: illuminance

      spare_room_battery_level:
        friendly_name: 'Spare Room Battery Level'
        value_template: '{{ states.binary_sensor.spare_room_motion_sensor.attributes.battery }}'
        unit_of_measurement: '%'
        device_class: battery
      spare_room_lumens:
        friendly_name: 'Spare Room Lumens'
        value_template: '{{ states.binary_sensor.spare_room_motion_sensor.attributes.light_level }}'
        unit_of_measurement: Lumens
        device_class: illuminance

      sun_room_battery_level:
        friendly_name: 'Sun Room Battery Level'
        value_template: '{{ states.binary_sensor.sun_room_motion_sensor.attributes.battery }}'
        unit_of_measurement: '%'
        device_class: battery
      sun_room_lumens:
        friendly_name: 'Sun Room Lumens'
        value_template: '{{ states.binary_sensor.sun_room_motion_sensor.attributes.light_level }}'
        unit_of_measurement: Lumens
        device_class: illuminance

      distance_apart:
        friendly_name: 'GandG Apart'
        value_template: >-
          {% if distance(states.device_tracker.iphone, states.device_tracker.grdems_phone_2) | int == 0 %}
            0
          {% elif distance(states.device_tracker.iphone, states.device_tracker.grdems_phone_2) | round(2) < 0.09 %}
            0
          {% else %}
            {{ distance(states.device_tracker.iphone, states.device_tracker.grdems_phone_2) | round(2) }}
          {% endif %}
        unit_of_measurement: 'km'
        entity_id:
          - device_tracker.grdems_phone_2
          - device_tracker.iphone_2

  - platform: imap_email_content
    name: Fing State
    server: !secret fing_email_server
    port: 993
    username: !secret fing_email_username
    password: !secret fing_email_password
    senders:
      - alert@fing.io
      - alert@fing.com

  - platform: environment_canada

  # Sensor for monitoring the bridge state
  - platform: mqtt
    name: Zigbee2mqtt Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless
  # Sensor for Showing the Zigbee2mqtt Version
  - platform: mqtt
    name: Zigbee2mqtt Version
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.version }}"
    icon: mdi:zigbee
  # Sensor for Showing the Coordinator Version
  - platform: mqtt
    name: Coordinator Version
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.coordinator }}"
    icon: mdi:chip


binary_sensor:
  - platform: workday
    country: CA
    province: PE

  - platform: huesensor

# }}}
# {{{ Switches

# Wemo switches are not always being discovered automatically.
wemo:
  static:
    - 192.168.2.80
    # Died - 192.168.2.81
    - 192.168.2.82
    - 192.168.2.83

tplink:
  switch:
    - host: 192.168.2.84
    - host: 192.168.2.85
    - host: 192.168.2.87
    - host: 192.168.2.88
    - host: 192.168.2.89

# }}}
# {{{ Text-to-speech
tts:
  - platform: google_translate
    service_name: google_say

  - platform: voicerss
    api_key: !secret voicerss_api_key

# }}}
# {{{ Weather

weather:
  - platform: environment_canada

# }}}

group: !include groups.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml
