# vim: set expandtab tabstop=2 shiftwidth=2 softtabstop=2:
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 25
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Halifax

# {{{ customizations

  customize:
    group.all_devices:
      hidden: false
    group.all_scripts:
      hidden: false
    group.all_automations:
      hidden: false
    group.all_booleans:
      hidden: false
    group.all_lights:
      hidden: false
    group.all_switches:
      hidden: false

# }}}
# {{{ misc

# Enable web configs
config:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Set logging level
logger:
  default: error
  logs:
    homeassistant.components.camera: fatal
    homeassistant.components.media_player.plex: fatal

# Wemo switches are not always being discovered automatically.
wemo:
  static:
    - 192.168.2.80
    - 192.168.2.81

# Hue lights are not being discovered automaically.
light:
  platform: hue
  host: 192.168.2.120
  allow_unreachable:

# Lutron Dimmers in Kitchen
lutron_caseta:
  host: 192.168.2.121

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# Setup db
recorder:
  purge_days: 2

# View all events in a logbook
logbook:

# Track the sun
sun:

ifttt:
  key: !secret ifttt_key

ffmpeg:
  run_test: false

# Enable IOS component
ios:

# }}}
# {{{ text-to-speech
tts:
  - platform: google

  - platform: voicerss
    api_key: !secret voicerss_api_key

# }}}
# {{{ zones

zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 50
  icon: mdi:home

zone silverorange:
  name: silverorange
  latitude: !secret silverorange_latitude
  longitude: !secret silverorange_longitude
  radius: 50
  icon: mdi:domain

zone upstreet:
  name: Upstreet
  latitude: !secret upstreet_latitude
  longitude: !secret upstreet_longitude
  radius: 30
  icon: mdi:beer

zone innovatia:
  name: Innovatia
  latitude: !secret innovatia_latitude
  longitude: !secret innovatia_longitude
  radius: 100
  icon: mdi:domain

zone walmart:
  name: Walmart
  latitude: !secret walmart_latitude
  longitude: !secret walmart_longitude
  radius: 100
  icon: mdi:shopping

zone churchill_arms:
  name: Churchill Arms
  latitude: !secret churchill_arms_latitude
  longitude: !secret churchill_arms_longitude
  radius: 50
  icon: mdi:beer

zone delta_calgary_downtown:
  name: Calgary Delta
  latitude: 51.048800
  longitude: -114.059662
  radius: 50
  icon: mdi:hotel

zone yyc:
  name: Calgary Airport
  latitude: 51.125061
  longitude: -114.016889
  radius: 100
  icon: mdi:airplane

zone yyg:
  name: Charlottetown Airport
  latitude: 46.286076
  longitude: -63.131658
  radius: 200
  icon: mdi:airplane

zone yeg:
  name: Edmonton Airport
  latitude: 53.327848
  longitude: -113.566524
  radius: 100
  icon: mdi:airplane

zone yhz:
  name: Halifax Airport
  latitude: 44.887088
  longitude: -63.515278
  radius: 400
  icon: mdi:airplane

zone yul:
  name: Montreal Airport
  latitude: 45.458942
  longitude: -73.750330
  radius: 400
  icon: mdi:airplane

zone yyz:
  name: Pearson Airport
  latitude: 43.679232
  longitude: -79.620109
  radius: 1000
  icon: mdi:airplane

zone ytz:
  name: Toronto City Central Airport
  latitude: 43.628482
  longitude: -79.395958
  radius: 400
  icon: mdi:airplane

zone yjz:
  name: Saint John Airport
  latitude: 45.326501
  longitude: -65.888867
  radius: 400
  icon: mdi:airplane

zone yyt:
  name: "St. John's Airport"
  latitude: 47.621210
  longitude: -52.742443
  radius: 400
  icon: mdi:airplane

# }}}
# {{{ frontend

# Enables the frontend
frontend:

http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  use_x_forwarded_for: true
  trusted_networks:
    - 192.168.2.0/24
    - 127.0.0.1

# }}}
## {{{ Media Players
#
#media_player:
#
## Spotify
#  - platform: spotify
#    client_id: !secret spotify_client_id
#    client_secret: !secret spotify_client_secret
#
## }}}
# {{{ Ring

ring:
  username: !secret ring_username
  password: !secret ring_password

# }}}
# {{{ Sensors

sensor:
  - platform: pi_hole
    host: pi.hole

  - platform: command_line
    name: 'HASS uptime'
    command: echo "$(($(date +%s) - $(date --date="`systemctl show home-assistant.service -p ActiveEnterTimestamp | awk -F'=' '{print $2}'`" "+%s")))"
    scan_interval: 60
    unit_of_measurement: minutes
    value_template: >-
      {% set uptime = value | int %}
      {% set minutes = (uptime / 60 ) | int %}
      {{ minutes }}

  - platform: moon

  - platform: ring
    monitored_conditions:
      - last_activity
      - last_ding
      - last_motion
      - volume

  - platform: speedtest
    hour:
      - 4
    monitored_conditions:
      - ping
      - download
      - upload

  - platform: rest
    resource: !secret hue_livingroom_battery
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 86400
    name: 'Living Room Battery Level'

  - platform: rest
    resource: !secret hue_livingroom_lightlevel
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: 'Living Room Lux'

  - platform: rest
    resource: !secret hue_livingroom_temp
    value_template: '{{ value_json.state.temperature | round(-1) | float / 100 }}'
    unit_of_measurement: °C
    name: 'Living Room Temp'

  - platform: yr
    monitored_conditions:
      - temperature
      - symbol

  - platform: wunderground
    api_key: !secret wunderground_api_key
    monitored_conditions:
      - alerts
      - feelslike_c
      - heat_index_c
      - pressure_trend
      - relative_humidity
      - solarradiation
      - temp_c
      - UV
      - visibility_km
      - weather
      - wind_degrees
      - wind_gust_kph
      - wind_kph

  - platform: yweather
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature

  - platform: plex
    host: plex
    username: !secret plex_username
    password: !secret plex_password

  - platform: crimereports
    name: Crime Reports
    radius: 5000

binary_sensor:
  - platform: workday
    country: CA
    province: PE

  - platform: rest
    name: Livingroom Status
    resource: !secret hue_livingroom_status
    value_template: '{{ value_json.state.status }}'
    scan_interval: 2

  - platform: rest
    name: Livingroom Motion
    resource: !secret hue_livingroom_presence
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2

  - platform: ring
    monitored_conditions:
      - ding
      - motion

# }}}
# {{{ Presence Trackers

device_tracker:
#  - platform: asuswrt
#    host: 192.168.2.249
#    username: !secret router_username
#    mode: ap
#    protocol: ssh
#    ssh_key: /home/homeassistant/.ssh/id_rsa
#
#  - platform: asuswrt
#    host: 192.168.2.252
#    username: !secret router_username
#    password: !secret router_password
#    mode: ap
#    protocol: telnet

  - platform: nmap_tracker
    hosts: 192.168.2.1-9
    home_interval: 5

  - platform: nmap_tracker
    hosts: 192.168.2.10-14
    home_interval: 15

  - platform: nmap_tracker
    hosts: 192.168.2.15-100
    home_interval: 5
    exclude:
      - 192.168.2.150

  - platform: nmap_tracker
    hosts: 192.168.2.101-254
    home_interval: 5

  - platform: ping
    count: 10
    hosts:
      Jennifer2: jen-phone
      Cameron2: cam-phone
      Grant2: grant-phone
      Gervais3: iphone
      Gail3: Gail-iPhone

# }}}
# {{{ Toggles

input_boolean:
  loop_livingcolours:
    name: Loop Livingroom Colours
    initial: off
    icon: mdi:spotlight

input_slider:
  livingroom_brightness:
    name: Livingroom Brightness
    initial: 255
    min: 0
    max: 255
    step: 1

# }}}
# {{{ Security Cams

#camera:
android_ip_webcam:
  - name: 'Front Door Camera'
    host: 192.168.2.92
    scan_interval: 1
    sensors:
      - battery_voltage
      - light
      - motion
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording

# }}}
# {{{ Notify

notify:
  - name: zulip
    platform: rest
    resource: !secret zulip_notify_resource
    method: POST_JSON
    title_param_name: topic

# }}}
## {{{ Rest Commands

rest_command:
  sabnzb_api:
    url: !secret sabnzbd_rest_url

  take_a_picture:
    url: http://192.168.2.92:8080/photo_save_only.jpg

## }}}

group: !include groups.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml
