# vim: set expandtab tabstop=2 shiftwidth=2 softtabstop=2:

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 5
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Halifax
  # Allow homeassistant to write to snapshots dir
  whitelist_external_dirs:
    - /var/www/html/snapshots
  customize: !include customize.yaml

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.2.0/24
        - 127.0.0.1

# {{{ frontend

# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/

http:
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

weblink:
  entities:
    - name: Home Security
      url: https://home.demontbrun.com/snapshots/
      icon: mdi:file-video

# }}}
# {{{ Media Players

# Roku
roku:
  - host: 192.168.2.18
  - host: 192.168.2.130

media_player:

# Plex
  - platform: plex

# Alexa
alexa_media:
  accounts:
    - email: !secret alexa_username
      password: !secret alexa_password
      url: !secret alexa_url

# }}}
# {{{ Misc

# Enable frontend configuration
config:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Set logging level
logger:
  default: error
  logs:
    homeassistant.components.camera: fatal
    homeassistant.components.media_player.plex: fatal
    homeassistant.components.media_player.roku: fatal
    homeassistant.components.http.ban: warning

# Hue lights are not being discovered automaically.
hue:
  bridges:
    - host: 192.168.2.120
      allow_unreachable: true

# Homekit Setup
homekit:
  filter:
    include_domains:
      - light
      - media_player
      - switch

# Lutron Dimmers
lutron_caseta:
  host: 192.168.2.121
  keyfile: 'lutron/caseta.key'
  certfile: 'lutron/caseta.crt'
  ca_certs: 'lutron/caseta-bridge.crt'

# Enables support for tracking state changes over time.
history:
  include:
    entities:
      - person.gail
      - person.gervais

# Setup recorder
recorder:

# Track the sun
sun:

ifttt:
  key: !secret ifttt_key

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# Enable IOS component
ios:

downloader:
  download_dir: /var/www/html/snapshots

system_health:

speedtestdotnet:
  scan_interval:
    hours: 8
  monitored_conditions:
    - ping
    - download
    - upload

# }}}
# {{{ Notify

notify:
  - name: zulip
    platform: rest
    resource: !secret zulip_notify_resource
    method: POST_JSON
    title_param_name: topic

# }}}
# {{{ Persons

person:
  - name: Gervais
    id: gevais1968
    user_id: 552babcc7c9f490191d97de847350f77
    device_trackers:
      - device_tracker.iphonehass
      - device_tracker.gervais_fing
      - device_tracker.gervais_owntracks
  - name: Gail
    id: gail1968
    user_id: 1b937317d2a242d7af7df282b35359b1
    device_trackers:
      - device_tracker.dgrabbs_iphonehass
      - device_tracker.gail_fing
      - device_tracker.gail_owntracks
  - name: Cameron
    id: cam1995
    device_trackers:
      - device_tracker.camphone
      - device_tracker.cameron2
      - device_tracker.cam_fing
  - name: Grant
    id: grant1994
    device_trackers:
      - device_tracker.grantphone
      - device_tracker.grant2
      - device_tracker.grant_fing
  - name: Jennifer
    id: jen2000
    device_trackers:
      - device_tracker.jenphone
      - device_tracker.jennifer2
      - device_tracker.jen_fing

# }}}
# {{{ Presence Trackers

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.2.10-15
    home_interval: 5
    interval_seconds: 120
    new_device_defaults:
      track_new_devices: true
      hide_if_away: true

  - platform: ping
    count: 10
    hosts:
      Cameron2: cam-phone
      Gail3: Gail-iPhone
      Gervais3: iphone
      Grant2: grant-phone
      Jennifer2: jen-phone
      Router: router

# }}}
## {{{ Rest Commands

rest_command:
  sabnzb_api:
    url: !secret sabnzbd_rest_url

  take_a_picture:
    url: http://192.168.2.92:8080/photo_save_only.jpg

## }}}
# {{{ Ring

ring:
  username: !secret ring_username
  password: !secret ring_password

# }}}
# {{{ Security Cams

camera:
  - platform: ring
    scan_interval: 90

# }}}
# {{{ Sensors

sensor:
  - platform: whois
    domain: demontbrun.com
    name: deMontbrun DNS Expiry

  - platform: season

  - platform: cert_expiry
    host: !secret http_base_url

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use_percent
        arg: /boot
      - type: disk_use_percent
        arg: /media/apple
      - type: disk_use_percent
        arg: /media/wine
      - type: disk_use_percent
        arg: /media/cracker
      - type: disk_use_percent
        arg: /media/grapes
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: swap_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use
      - type: last_boot

  - platform: glances
    host: zulip.dem
    name: zulip
    resources:
      - 'disk_use_percent'
      - 'memory_use_percent'
      - 'swap_use_percent'
      - 'processor_load'

  - platform: command_line
    name: 'Pi CPU temp'
    command: curl -sL http://pi.hole | grep Temp | awk '{ print $11 }' | sed 's/Temp:&nbsp;//' | sed 's/&nbsp;&deg;C<\/a>//'
    unit_of_measurement: °C

  - platform: command_line
    name: 'Grater uptime'
    command: cat /proc/uptime | awk '{ print $1 }'
    scan_interval: 60
    unit_of_measurement: minutes
    value_template: >-
      {% set uptime = value | int %}
      {% set minutes = (uptime / 60 ) | int %}
      {{ minutes }}

  - platform: uptime
    name: 'HASS uptime'
    unit_of_measurement: hours

  - platform: moon

  - platform: ring
    monitored_conditions:
      - last_activity
      - last_ding
      - last_motion

  - platform: rest
    resource: !secret hue_bedroom_battery
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 86400
    name: 'Bed Room Battery Level'

  - platform: rest
    resource: !secret hue_bedroom_lightlevel
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: 'Bed Room Lux'

  - platform: rest
    resource: !secret hue_bedroom_temp
    value_template: '{{ value_json.state.temperature | round(-1) | float / 100 }}'
    unit_of_measurement: °C
    name: 'Bed Room Temp'

  - platform: rest
    resource: !secret hue_livingroom_battery
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 86400
    name: 'Living Room Battery Level'

  - platform: rest
    resource: !secret hue_livingroom_lightlevel
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: 'Living Room Lux'

  - platform: rest
    resource: !secret hue_livingroom_temp
    value_template: '{{ value_json.state.temperature | round(-1) | float / 100 }}'
    unit_of_measurement: °C
    name: 'Living Room Temp'

  - platform: yr
    monitored_conditions:
      - temperature
      - symbol

  - platform: command_line
    name: 'filesize_db'
    command: 'stat -c %s "/etc/homeassistant/home-assistant_v2.db"'
    unit_of_measurement: 'MB'
    value_template: '{{ (value|int / 1024 / 1024)|round(1) }}'
    scan_interval: 900

  - platform: template
    sensors:
      distance_apart:
        friendly_name: 'GandG Apart'
        value_template: >-
          {% if distance(states.device_tracker.gervais_owntracks, states.device_tracker.gail_owntracks) | int == 0 %}
            0
          {% elif distance(states.device_tracker.gervais_owntracks, states.device_tracker.gail_owntracks) | round(2) < 0.09 %}
            0
          {% else %}
            {{ distance(states.device_tracker.gervais_owntracks, states.device_tracker.gail_owntracks) | round(2) }}
          {% endif %}
        unit_of_measurement: 'km'
        entity_id:
          - device_tracker.gail_owntracks
          - device_tracker.gervais_owntracks

  - platform: imap_email_content
    name: Fing State
    server: !secret fing_email_server
    port: 993
    username: !secret fing_email_username
    password: !secret fing_email_password
    senders:
      - alert@fing.io
      - alert@fing.com

  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - apparent_temperature
      - humidity
      - nearest_storm_distance
      - temperature
      - temperature_high
      - temperature_low
      - summary
      - wind_bearing
      - wind_gust
      - wind_speed
      - uv_index
    units: ca
    scan_interval:
      hours: 1

binary_sensor:
  - platform: workday
    country: CA
    province: PE

  - platform: rest
    name: Bedroom Motion
    resource: !secret hue_bedroom_status
    value_template: '{{ value_json.state.status }}'
    scan_interval: 2

  - platform: rest
    name: Bedroom Presence
    resource: !secret hue_bedroom_presence
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2

  - platform: rest
    name: Livingroom Motion
    resource: !secret hue_livingroom_status
    value_template: '{{ value_json.state.status }}'
    scan_interval: 2

  - platform: rest
    name: Livingroom Presence
    resource: !secret hue_livingroom_presence
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2

  - platform: ring
    monitored_conditions:
      - ding
      - motion

# }}}
# {{{ Switches

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: !secret tuya_country_code

# Wemo switches are not always being discovered automatically.
wemo:
  static:
    - 192.168.2.80
    - 192.168.2.81
    - 192.168.2.82
    - 192.168.2.83
tplink:
  switch:
    - host: 192.168.2.84
    - host: 192.168.2.85
    - host: 192.168.2.87
    - host: 192.168.2.88
    - host: 192.168.2.89

switch:
  - platform: broadlink
    host: 192.168.2.7
    mac: '34:EA:34:43:15:05'
    timeout: 20
    switches:
      tv_power:
        friendly_name: 'TV Power'
        command_on: 'JgBYAAABKJYRExIUETkRFBEUERUQFBEUETkROREUETkRORE5EjgSOBITEhQRFBI4ERQRFBEUERUQORE5ETkRFBE5ETkRORE5EgAFMAABKEwRAAxtAAEoSxIADQU='
        command_off: 'JgBYAAABKJYRExIUETkRFBEUERUQFBEUETkROREUETkRORE5EjgSOBITEhQRFBI4ERQRFBEUERUQORE5ETkRFBE5ETkRORE5EgAFMAABKEwRAAxtAAEoSxIADQU='
      tv_mute:
        friendly_name: 'TV Mute'
        command_on: 'JgBYAAABKZQSExITEjkRFBEUERQRFBEUETkROREUETkRORE5ETkSORE5ERQRFBE5ERQRFBEUERQRFBE5ETkRFBE5ETkSOBI4EgAFMAABKUoRAAxsAAEpSxEADQU='
        command_off: 'JgBYAAABKZQSExITEjkRFBEUERQRFBEUETkROREUETkRORE5ETkSORE5ERQRFBE5ERQRFBEUERQRFBE5ETkRFBE5ETkSOBI4EgAFMAABKUoRAAxsAAEpSxEADQU='

# }}}
# {{{ Text-to-speech
tts:
  - platform: google_translate
    service_name: google_say

  - platform: voicerss
    api_key: !secret voicerss_api_key

# }}}
# {{{ Weather

weather:
  - platform: darksky
    name: sj
    api_key: !secret darksky_api_key
    mode: daily
    scan_interval:
      hours: 1


# }}}
# {{{ zones

zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 80
  icon: mdi:home

zone craft_beer_corner:
  name: Craft Beer Corner
  latitude: !secret craft_beer_corner_latitude
  longitude: !secret craft_beer_corner_longitude
  radius: 20
  icon: mdi:beer

zone discoverygarden:
  name: discoverygarden
  latitude: !secret discoverygarden_latitude
  longitude: !secret discoverygarden_longitude
  radius: 50
  icon: mdi:domain

zone upstreet:
  name: Upstreet
  latitude: !secret upstreet_latitude
  longitude: !secret upstreet_longitude
  radius: 30
  icon: mdi:beer

zone innovatia:
  name: Innovatia
  latitude: !secret innovatia_latitude
  longitude: !secret innovatia_longitude
  radius: 100
  icon: mdi:domain

zone walmart:
  name: Walmart - Charlottetown
  latitude: !secret walmart_latitude
  longitude: !secret walmart_longitude
  radius: 100
  icon: mdi:shopping

zone churchill_arms:
  name: Churchill Arms
  latitude: !secret churchill_arms_latitude
  longitude: !secret churchill_arms_longitude
  radius: 25
  icon: mdi:beer

zone qeh:
  name: Queen Elizabeth Hospital
  latitude: !secret qeh_latitude
  longitude: !secret qeh_longitude
  radius: 200
  icon: mdi:hospital-building

zone delta_calgary_downtown:
  name: Calgary Delta
  latitude: 51.048800
  longitude: -114.059662
  radius: 50
  icon: mdi:hotel

zone confederation_bridge:
  name: Confederation Bridge
  latitude: 46.200184
  longitude: -63.765234
  radius: 4000
  icon: mdi:bridge

# Airports
zone yyc:
  name: Calgary Airport
  latitude: 51.131686
  longitude: -114.006702
  radius: 600
  icon: mdi:airplane

zone yyg:
  name: Charlottetown Airport
  latitude: 46.286076
  longitude: -63.131658
  radius: 200
  icon: mdi:airplane

zone yeg:
  name: Edmonton Airport
  latitude: 53.307505
  longitude: -113.584352
  radius: 600
  icon: mdi:airplane

zone yhz:
  name: Halifax Airport
  latitude: 44.887088
  longitude: -63.515278
  radius: 400
  icon: mdi:airplane

zone yul:
  name: Montreal Airport
  latitude: 45.458942
  longitude: -73.750330
  radius: 400
  icon: mdi:airplane

zone yyz:
  name: Pearson Airport
  latitude: 43.679232
  longitude: -79.620109
  radius: 1000
  icon: mdi:airplane

zone ytz:
  name: Toronto City Central Airport
  latitude: 43.628482
  longitude: -79.395958
  radius: 400
  icon: mdi:airplane

zone ysj:
  name: Saint John Airport
  latitude: 45.326501
  longitude: -65.888867
  radius: 600
  icon: mdi:airplane

zone yyt:
  name: "St. John's Airport"
  latitude: 47.621210
  longitude: -52.742443
  radius: 400
  icon: mdi:airplane

# }}}

group: !include groups.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml
