title: home
views:
  - cards:
      - cards:
          - entities:
              - entity: device_tracker.gail_219d5f91_3462_4a44_9c44_e159026137b6
              - entity: device_tracker.gervais_56f37929_02ce_4cc0_ab26_033d09334375
              - entity: group.cam_tracker
              - entity: group.jen_tracker
            show_header_toggle: false
            title: Household Members
            type: entities
          - type: conditional
            conditions:
              - entity: sensor.distance_apart
                state: '> 1'
            card:
              entity: sensor.distance_apart
              max: 4000
              min: 0
              name: GandG Apart
              severity:
                green: 0
                red: 1000
                yellow: 200
              theme: default
              type: gauge
        type: vertical-stack
      - entities:
          - entity: device_tracker.gail_219d5f91_3462_4a44_9c44_e159026137b6
          - entity: device_tracker.gervais_56f37929_02ce_4cc0_ab26_033d09334375
        type: map
    badges: []
    icon: 'mdi:account-multiple'
    path: default-view
    title: People
    panel: false
  - badges: []
    cards:
      - entities:
          - group.all_lights
          - group.outdoor_lights
          - group.mainfloor_lights
          - group.secondfloor_lights
          - group.bedroom_lights
          - group.spareroom_lights
          - group.kitchen_lights
          - group.livingroom_lights
          - group.office_lights
        show_header_toggle: false
        title: All lights
        type: entities
      - entities:
          - entity: group.bedroom_lights
          - entity: light.bedroom0
          - entity: light.bedroom1
          - entity: light.bedroom2
          - switch.switch4
        type: entity-filter
        state_filter:
          - 'on'
          - 'off'
        card:
          title: Bedroom
          show_header_toggle: false
      - type: entity-filter
        entities:
          - entity: group.livingroom_lights
          - light.couch0
          - light.couch1
          - light.fireplace0
          - light.fireplace1
          - light.fireplace2
          - light.fireplace3
          - light.lamp
          - switch.switch2
        state_filter:
          - 'on'
          - 'off'
        card:
          show_header_toggle: false
          title: Livingroom
      - entities:
          - group.spareroom_lights
          - light.computer_room
          - light.spare0
          - light.spare1
        show_header_toggle: false
        title: Spare rooms
        type: entities
      - entities:
          - group.office_lights
          - light.office_main_lights
          - switch.switch0
          - switch.switch3
          - switch.switch5
        type: entity-filter
        state_filter:
          - 'on'
          - 'off'
        card:
          show_header_toggle: false
          title: Office
      - entities:
          - entity: light.bathroom
          - entity: light.hallway
        show_header_toggle: true
        title: Misc Lights
        type: entities
      - entities:
          - entity: group.kitchen_lights
          - entity: light.kitchen_island
          - entity: light.kitchen_oven
          - entity: light.kitchen_table
          - entity: light.kitchen_window
        show_header_toggle: false
        title: Kitchen
        type: entities
      - entities:
          - entity: group.outdoor_lights
          - entity: light.front_door
          - entity: light.backdoor0
          - entity: light.backdoor1
        show_header_toggle: false
        title: Outdoor lights
        type: entities
      - entities:
          - entity: switch.tv_power
          - entity: switch.tv_mute
        show_header_toggle: false
        title: TV
        type: entities
    icon: 'mdi:lightbulb'
    title: Lights and Switches
  - badges: []
    cards:
      - entity: weather.dark_sky
        name: Forecast
        type: weather-forecast
      - entities:
          - entity: sensor.pws_weather
          - entity: sun.sun
          - entity: sensor.moon
          - entity: sensor.season
        show_header_toggle: false
        title: Weather
        type: entities
    icon: 'mdi:weather-partlycloudy'
    title: Weather
  - badges: []
    cards:
      - camera_image: camera.front_door
        entity: camera.front_door
        show_info: true
        title: Front Door
        type: picture-entity
      - entities:
          - icon: 'mdi:file-video'
            name: Home Security
            type: weblink
            url: 'https://home.demontbrun.com/snapshots/'
        show_header_toggle: false
        title: Recordings
        type: entities
    icon: 'mdi:video'
    title: Security
  - badges: []
    cards:
      - entity: media_player.living_room_roku
        type: media-control
      - entity: media_player.plex_livingroom
        type: media-control
      - entity: media_player.office
        type: media-control
      - entity: media_player.plex_keypear
        type: media-control
    icon: 'mdi:play-circle-outline'
    title: Media Players
  - badges: []
    cards:
      - entities:
          - automation.timed_lights_movement_in_livingroom
          - automation.everyone_home_and_gone_to_bed_lights_out
          - automation.set_sabnzb_speed_limit
          - automation.midnight_livingroom_lights_out
          - automation.home_presence_notification
          - automation.2am_lights_out
          - automation.phones_presence_notification
          - automation.6pm_heater_off
          - automation.current_weather_notification
          - automation.sunrise_lights_out
          - automation.current_uv_index_notification
          - automation.sunset_lights_on
          - automation.weather_alert_notification
          - automation.sunset_office_lights_on
          - automation.weather_forecast_notification
          - automation.living_room_lux_low_lights_on
          - automation.gandg_not_home_movement_in_bedroom
          - automation.jennifer_home_turn_on
          - automation.drive_is_filling
          - automation.jennifer_away_turn_off
          - automation.turn_off_livingroom_tv_when_idle
          - automation.midnight_heater_off
          - automation.gail_away_sonos_speaker_set_sleep_timer
          - automation.bedroom_window_fan_on
          - automation.gail_home_sonos_speaker_clear_sleep_timer
          - automation.bedroom_window_fan_off
          - automation.pause_sonos_every_2_minutes_if_gail_away
          - automation.livingroom_window_fan_on
          - automation.turn_on_heater_in_bedroom
          - automation.livingroom_window_fan_off
          - automation.plex_paused_stopped_normal_lights
          - automation.turn_off_heater_in_bedroom
          - automation.gail_away_turn_off_heater
          - automation.germaine_arrives
          - automation.gail_home_turn_on_heater
          - automation.germaine_leaves
          - automation.bedtime
          - automation.plex_playing_dimm_lights
          - automation.gandg_not_home_turn_off_bedroom_things
          - automation.fing_update_user
          - automation.roku_idle
          - automation.tell_jen_to_turn_off_her_tv
          - automation.roku_playing
          - automation.timed_lights_movement_front_door
          - automation.gandg_playing
          - automation.doorbell_rang_pause_tv
          - automation.gandg_paused
          - automation.doorbell_notify
        show_header_toggle: false
        title: Automations
        type: entities
      - cards:
          - entities:
              - scene.livingroom_dim
              - scene.livingroom_normal
              - scene.livingroom_nightlight
              - scene.caseta_lights_off
              - scene.kitchen_one_percent
              - scene.kitchen_off
            show_header_toggle: false
            title: Scene
            type: entities
          - entities:
              - script.timed_livingroom
              - script.timer_outdoor_off
              - script.timed_outdoor
              - script.timer_livingroom_off
            show_header_toggle: false
            title: Script
            type: entities
        type: vertical-stack
    icon: 'mdi:wrench-outline'
    path: ''
    title: Settings
