resources: []
title: ''
views:
  - badges: []
    cards:
      - cards:
          - entities:
              - entity: person.gail
              - entity: person.gervais
              - entity: person.jennifer
            show_header_toggle: false
            title: Household Members
            type: entities
          - card: null
            entities:
              - entity: person.chris
              - entity: person.jamie
            show_header_toggle: false
            title: Tenants
            type: entities
          - card:
              entity: sensor.distance_apart
              max: 4000
              min: 0
              name: GandG Apart
              severity:
                green: 0
                red: 1000
                yellow: 200
              theme: default
              type: gauge
            conditions:
              - entity: sensor.distance_apart
                state_not: '0'
            type: conditional
        type: vertical-stack
      - dark_mode: false
        entities:
          - entity: person.jennifer
          - entity: person.cameron
          - entity: device_tracker.iphone
          - entity: device_tracker.grdems_phone_2
        type: map
    icon: 'mdi:account-multiple'
    panel: false
    path: default-view
    title: People
  - badges: []
    cards:
      - entities:
          - entity: group.outdoor_lights
          - entity: group.mainfloor_lights
          - entity: group.secondfloor_lights
          - entity: group.bathroom_lights
          - entity: group.bedroom_lights
          - entity: group.diningroom_lights
          - entity: group.dressing_room_lights
          - entity: group.hallway_lights
          - entity: group.kitchen_lights
          - entity: group.livingroom_lights
          - entity: group.office_lights
          - entity: group.sunroom_lights
        show_header_toggle: false
        title: All Lights
        type: entities
      - card:
          show_header_toggle: false
          title: Bathroom
        entities:
          - entity: group.bathroom_lights
          - entity: switch.bathroom0
          - entity: switch.bathroom1
          - entity: switch.bathroom2
        state_filter:
          - 'on'
          - 'off'
        type: entity-filter
      - card:
          show_header_toggle: false
          title: Bedroom
        entities:
          - entity: group.bedroom_lights
          - switch.circadian_lighting_bedroom_circadian
          - entity: light.bedroom0
          - entity: light.bedroom1
          - entity: light.bedroom2
          - entity: light.bedroom3
          - entity: light.bedroom4
          - switch.switch4
        state_filter:
          - 'on'
          - 'off'
        type: entity-filter
      - card:
          show_header_toggle: false
          title: Dining Room
        entities:
          - entity: group.diningroom_lights
          - entity: light.diningroom0
          - entity: light.diningroom1
        state_filter:
          - 'on'
          - 'off'
        type: entity-filter
      - entities:
          - entity: group.dressing_room_lights
          - entity: light.dressing_room0
          - entity: light.dressing_room1
          - entity: light.dressing_room2
          - entity: light.dressing_room3
        show_header_toggle: false
        title: Dressing Room
        type: entities
      - card:
          show_header_toggle: false
          title: Hallway
        entities:
          - entity: group.hallway_lights
          - entity: light.stairs_back
          - entity: light.cherub
          - entity: light.foyer
          - entity: light.hallway_wall
          - entity: light.upstairshallway
          - entity: switch.switch0
        state_filter:
          - 'on'
          - 'off'
        type: entity-filter
      - card:
          show_header_toggle: false
          title: Kitchen
        entities:
          - entity: group.kitchen_lights
          - entity: light.kitchen_island
          - entity: light.kitchen_pots
          - entity: light.kitchen_swirly0
          - entity: light.kitchen_swirly1
        state_filter:
          - 'on'
          - 'off'
        type: entity-filter
      - card:
          show_header_toggle: false
          title: Livingroom
        entities:
          - entity: group.livingroom_lights
          - entity: light.lamp0
          - entity: light.lamp1
          - entity: light.lamp2
          - entity: light.living_room_pendants0
          - entity: light.living_room_pendants1
          - entity: switch.switch2
        state_color: true
        state_filter:
          - 'on'
          - 'off'
        type: entity-filter
      - card:
          show_header_toggle: false
          title: Office
        entities:
          - group.office_lights
          - switch.circadian_lighting_office_circadian
          - light.office0
          - light.office1
          - switch.switch3
        state_filter:
          - 'on'
          - 'off'
        type: entity-filter
      - card:
          show_header_toggle: false
          title: Outdoor
        entities:
          - entity: group.outdoor_lights
          - entity: light.front_door
          - entity: switch.outdoor_backdoor
          - entity: switch.outdoor_deck_lights
        state_color: true
        state_filter:
          - 'on'
          - 'off'
        type: entity-filter
      - card:
          show_header_toggle: false
          title: Sunroom
        entities:
          - group.sunroom_lights
          - light.sunroom0
          - light.sunroom1
          - light.sunroom2
          - light.sunroom3
          - light.sunroom4
          - switch.switch6
        state_filter:
          - 'on'
          - 'off'
        type: entity-filter
      - card:
          show_header_toggle: false
          title: Misc
        entities:
          - entity: switch.basement_light
          - entity: light.main_floor_bathroom_light
          - entity: light.upstairsbathroom
        state_filter:
          - 'on'
          - 'off'
        type: entity-filter
    icon: 'mdi:lightbulb'
    title: Lights and Switches
  - badges: []
    cards:
      - entity: weather.sj
        name: in Saint John
        type: weather-forecast
      - entities:
          - entity: sun.sun
          - entity: sensor.dark_sky_summary
          - entity: sensor.dark_sky_temperature
          - entity: sensor.dark_sky_apparent_temperature
          - entity: sensor.dark_sky_wind_gust
          - entity: sensor.dark_sky_humidity
          - entity: sensor.dark_sky_uv_index
          - entity: sensor.dark_sky_nearest_storm_distance
        show_header_toggle: false
        type: entities
      - entities:
          - entity: climate.my_ecobee
          - entity: binary_sensor.my_ecobee_occupancy
          - entity: sensor.my_ecobee_temperature
          - entity: binary_sensor.living_room_occupancy
          - entity: sensor.living_room_temperature
          - entity: binary_sensor.office_occupancy
          - entity: sensor.office_temperature
          - entity: binary_sensor.jennifer_room_occupancy
          - entity: sensor.jennifer_room_temperature
          - entity: binary_sensor.master_bedroom_occupancy
          - entity: sensor.master_bedroom_temperature
          - entity: binary_sensor.upstair_hall_occupancy
          - entity: sensor.upstair_hall_temperature
          - entity: sensor.my_ecobee_humidity
        show_header_toggle: false
        state_color: true
        title: Eco Bee
        type: entities
      - entities:
          - entity: binary_sensor.kitchen_motion_sensor
          - entity: sensor.kitchen_temp
          - entity: binary_sensor.sun_room_motion_sensor
          - entity: sensor.sun_room_temp
          - entity: binary_sensor.bedroom_motion_sensor
          - entity: sensor.bed_room_temp
        show_header_toggle: false
        state_color: true
        title: Hue Sensors
        type: entities
    icon: 'mdi:weather-cloudy'
    panel: false
    title: Weather
  - badges: []
    cards:
      - camera_image: camera.front_door
        entity: camera.front_door
        show_info: true
        title: Front Door
        type: picture-entity
      - entities:
          - entity: weblink.home_security
            icon: 'mdi:file-video'
            name: Home Security
            type: weblink
            url: 'https://home.demontbrun.com/snapshots/'
        show_header_toggle: false
        title: Recordings
        type: entities
      - entities:
          - sensor.front_door_battery
          - binary_sensor.front_door_ding
          - sensor.front_door_last_activity
          - sensor.front_door_last_ding
          - sensor.front_door_last_motion
          - binary_sensor.front_door_motion
          - sensor.front_door_volume
        state_color: true
        type: entities
    icon: 'mdi:video'
    title: Security
  - badges: []
    cards:
      - entity: media_player.everywhere
        type: media-control
      - entity: media_player.bedroom
        type: media-control
      - entity: media_player.kitchen
        type: media-control
      - entity: media_player.office
        type: media-control
      - entity: media_player.sun_room
        type: media-control
      - entity: media_player.apt_a
        type: media-control
      - card:
          entity: media_player.plex_roku_3
          type: media-control
        conditions:
          - entity: media_player.plex_roku_3
            state_not: 'off'
          - entity: media_player.plex_roku_3
            state: playing
        type: conditional
      - card:
          entity: media_player.plex_xboxone
          type: media-control
        conditions:
          - entity: media_player.plex_xboxone
            state_not: 'off'
          - entity: media_player.plex_xboxone
            state: playing
        type: conditional
      - entity: media_player.plex_sunroom
        type: media-control
      - entity: media_player.roku_sunroom
        type: media-control
    icon: 'mdi:play-circle-outline'
    title: Media Players
